### ISSUE TITLE
register.html和link-service.html的tab跳转

### ISSUE THREAD

**Issue by MMMayC** [MMMayC/medicare-prototype#10]
怎么做到我点击这个tab上的图片，就跳到下一个tab？

**Comment by MMMayC** [comment]
![image](https://cloud.githubusercontent.com/assets/16255652/19575503/86818a7a-975a-11e6-94f7-f6b0cc5f9ed7.png)
点击这个login tab上的图片，然后跳到下一个tab choose service
![image](https://cloud.githubusercontent.com/assets/16255652/19575519/97a98a78-975a-11e6-9236-a4b517aabb84.png)

**Comment by Renqqq** [comment]
要点击log in这个 tab上面的哪个图片去跳转，有三个图片啊？
![image](https://cloud.githubusercontent.com/assets/17472128/19583552/49626162-9770-11e6-9eaf-cf10cdc40424.png)

**Comment by MMMayC** [comment]
点击整个图片 然后跳到下一个tab，随便点哪个图片
