### ISSUE TITLE
lodge claim - load a draft

### ISSUE THREAD

**Issue by MMMayC** [MMMayC/medicare-prototype#3]
![image](https://cloud.githubusercontent.com/assets/16255652/19505557/50a61322-960f-11e6-8876-64c869008207.png)

lodge claim 页面上点击load a draft然后选择一个draft以后，modal消失，左边虚线范围内显示image/invoice.png，右边表格自动填充
![image](https://cloud.githubusercontent.com/assets/16255652/19505572/9a61199e-960f-11e6-93e3-5c817abf94a7.png)

**Comment by Renqqq** [comment]
这个描述我不是很清楚你要做什么？右边表格自动填充是什么意思？在详细一点说一下
