### ISSUE TITLE
Lodge claim - choose from document / drag and drop

### ISSUE THREAD

**Issue by MMMayC** [MMMayC/medicare-prototype#4]
![image](https://cloud.githubusercontent.com/assets/16255652/19505616/090777e4-9610-11e6-8c6b-4cc74e694d80.png)
Lodge claim页面点击choose from document或者点击drag and drop区域后虚线区域内显示image/invoice.png
一秒后出现一个modal，modal里有一个progress bar和提示: Invoice identifying...
![image](https://cloud.githubusercontent.com/assets/16255652/19505687/91371a2a-9610-11e6-9012-bae57720530a.png)

再一秒后modal消失
右边表格自动填充（内容和load a draft一样）

**Comment by Renqqq** [comment]
@MMMayC 这个也不是很明白你要实现什么功能
