### ISSUE TITLE
login popover dismiss

### ISSUE THREAD

**Issue by MMMayC** [MMMayC/medicare-prototype#9]
在点击popover的链接“register now”或者“link service”后，popover消失

**Comment by Renqqq** [comment]
这个点击事件好像不执行动作，所以这个popover换成那种不需要单击login就能出现的组件，我先做一下。如果你已经实现的话就关掉这个 @MMMayC

**Comment by Renqqq** [comment]
我把这个popover换成那种鼠标离开之后就隐藏的方式，这样的话就可以实现这个功能了，感觉这样的话效果还是挺好的 @MMMayC
